### ISSUE TITLE
i can't see any feature modules, so

### ISSUE THREAD

**Issue by MasterOfTouch** [anonlatte/Florarium#1]
https://github.com/anonlatte/Florarium/blob/74b03c7c2ccce80e98df5a3ca9c76c06e5a55e77/app/build.gradle#L78
![image](https://user-images.githubusercontent.com/37360486/148374496-c994e306-2f47-467b-911d-a16f18f701bd.png)

**Comment by anonlatte** [comment]
At the moment I don't have time to continue developing but wanna add more functionality in the future so this lib will help with navigation between different features
